############################################## - ⚓️ 锚点区开始 - ##############################################
# 锚点 - 筛选组
FilterSelect: &FilterSelect { filter: "^(?=.*(?i)(香港|🇭🇰|HK|台湾|🇹🇼|TW|日本|🇯🇵|JP|美国|🇺🇸|US|新加坡|狮城|🇸🇬|SG|韩国|首尔|🇰🇷|KR|KOR|英国|🇬🇧|UK|GB|德国|🇩🇪|DE))(?!.*(2.00x|排除2)).*$" }
FilterOthers: &FilterOthers { filter: "^(?!.*(DIRECT|Traffic|TRAFFIC|Expire|EXPIRE|流量|到期|时间|重置))" }
# 锚点 - 策略组
Select: &Select { type: select, include-all-providers: true, interrupt-exist-connections: true, proxies: [ "自动选择", "手动选择", "🌐 本地直连", "⛔️ 拒绝连接"] }
UrlTest: &UrlTest { type: url-test, interrupt-exist-connections: false, hidden: true, interval: 180, tolerance: 100, url: "https://captive.apple.com/generate_204" }
Fallback: &Fallback { type: fallback, interrupt-exist-connections: true, hidden: true, interval: 60, url: "https://captive.apple.com/generate_204" }
# 锚点 - 规则集
IPCIDR: &IPCIDR { type: http, interval: 86400, proxy: "订阅更新", behavior: ipcidr, format: mrs }
DOMAIN: &DOMAIN { type: http, interval: 86400, proxy: "订阅更新", behavior: domain, format: mrs }
CLASSICAL: &CLASSICAL { type: http, interval: 86400, proxy: "订阅更新", behavior: classical, format: text }
# 锚点 - 远程订阅组
Providers: &Providers { type: http, interval: 86400, proxy: "订阅更新", health-check: { enable: true, url: "https://captive.apple.com/generate_204", interval: 600 }, <<: *FilterOthers }
############################################## - ⚓️ 锚点区结束 - ##############################################

# 节点订阅
proxy-providers:
  守候: { <<: *Providers, url: "http://localhost:3000/download/SNTP", path: "./providers/守候.yaml", override: { additional-prefix: "[守候] " } }
  自建: { <<: *Providers, url: "http://localhost:3000/download/Node", path: "./providers/自建.yaml", override: { additional-prefix: "[自建] " } }

# 基础配置
mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
mode: rule
log-level: silent
ipv6: false
allow-lan: true
bind-address: "*"
unified-delay: true
tcp-concurrent: true
find-process-mode: always
authentication: [ "Ruruka:DaiSuiKi" ]
skip-auth-prefixes: [ "127.0.0.1/8", "::1/128" ]

external-ui-url: "https://v6.gh-proxy.org/github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
external-ui: "dashboard"
external-controller: 0.0.0.0:9090
secret: "RurukaSuki"

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  parse-pure-ip: true
  force-dns-mapping: true
  override-destination: false
  sniff: 
    HTTP: { ports: [ 80, 8080-8880 ], override-destination: true }
    TLS: { ports: [ 443, 8443 ] }
    QUIC: { ports: [ 443, 8443 ] }
  skip-domain: [ "rule-set:GeoSite-Sniffer-Filter" ]

hosts:
  "services.googleapis.cn": [ 64.233.188.94, 64.233.189.94 ]

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:1053
  cache-algorithm: arc
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-range6: fc00::/18
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - RULE-SET,GeoSite-AdBlock,real-ip
    - RULE-SET,GeoSite-FakeIP-Filter,real-ip
    - RULE-SET,GeoSite-Private,real-ip
    - RULE-SET,GeoSite-China,real-ip
    - MATCH,fake-ip
  nameserver-policy: { "rule-set:GeoSite-AdBlock": "rcode://success" }
  default-nameserver: [ 223.5.5.5, 119.29.29.29 ]
  nameserver: [ "https://dns.alidns.com/dns-query", "https://doh.pub/dns-query" ]

tun:
  enable: false
  mtu: 9000
  stack: mips
  device: Meta
  dns-hijack: [ "any:53", "tcp://any:53" ]
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true

proxies:
  - { name: "🌐 本地直连", type: direct }
  - { name: "⛔️ 拒绝连接", type: reject }
  - { name: "🔰 DNS-Hijack", type: dns }

proxy-groups:
  - { name: "自动选择", <<: [ *UrlTest, *FilterSelect ], include-all-providers: true, hidden: false, icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Auto.png" }
  - { name: "手动选择", type: select, include-all-providers: true, interrupt-exist-connections: true, icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Proxy.png" }
  - { name: "订阅更新", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Stack.png" }
  - { name: "谷歌推送", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Gmail.png" }
  - { name: "Telegram", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Telegram.png" }
  - { name: "Twitter", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Twitter.png" }
  - { name: "Emby", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Emby.png" }
  - { name: "E-Hentai", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Exhentai.svg" }
  - { name: "TikTok", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/TikTok.png" }
  - { name: "YouTube", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/YouTube.png" }
  - { name: "AI", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/ChatGPT.png" }
  - { name: "Games", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Game.png" }
  - { name: "Google", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Google_Search.png" }
  - { name: "Cloudflare", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Cloudflare.png" }
  - { name: "日本网站", <<: *Select, filter: "^(?=.*(?i)(日本|🇯🇵|JP))(?!.*(2.00x|排除2)).*$", icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Japan.png" }
  - { name: "台湾网站", <<: *Select, filter: "^(?=.*(?i)(香港|🇭🇰|HK|台湾|🇹🇼|TW))(?!.*(2.00x|排除2)).*$", icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Taiwan.png" }
  - { name: "国内直连", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/China.png" }
  - { name: "国外代理", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/United_Nations.png" }
  - { name: "广告拦截", type: select, proxies: [ "⛔️ 拒绝连接", "PASS" ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/AdBlack.png" }
  - { name: "漏网之鱼", <<: [ *Select, *FilterSelect ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Final.png" }
  - { name: "GLOBAL", <<: [ *Select, *FilterSelect ], proxies: [ "自动选择", "手动选择", "🌐 本地直连", "⛔️ 拒绝连接", "订阅更新", "谷歌推送", "Telegram", "Twitter", "Emby", "E-Hentai", "TikTok", "YouTube", "AI", "Games", "Google", "Cloudflare", "日本网站", "台湾网站", "国内直连", "国外代理", "广告拦截", "漏网之鱼" ], icon: "https://gh-proxy.com/github.com/MissToT/icon/raw/main/Global.png" }

rule-providers:
  GeoIP-China: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/china.mrs" }
  GeoIP-Proxy: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/proxy.mrs" }
  GeoIP-Private: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/private.mrs" }
  GeoIP-Telegram: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/telegram.mrs" }
  GeoIP-Twitter: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/twitter.mrs" }
  GeoIP-Google: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/google.mrs" }
  GeoIP-Cloudflare: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/cloudflare.mrs" }
  GeoIP-AI: { <<: *IPCIDR, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geoip/ai.mrs" }
  GeoSite-China: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/china.mrs" }
  GeoSite-Proxy: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/proxy.mrs" }
  GeoSite-Private: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/private.mrs" }
  GeoSite-Telegram: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/telegram.mrs" }
  GeoSite-Twitter: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/twitter.mrs" }
  GeoSite-Google: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/google.mrs" }
  GeoSite-GoogleFCM: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/googlefcm.mrs" }
  GeoSite-Cloudflare: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/cloudflare.mrs" }
  GeoSite-Games: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/games.mrs" }
  GeoSite-AI: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/ai.mrs" }
  GeoSite-Emby: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/emby.mrs" }
  GeoSite-Japan: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/japan.mrs" }
  GeoSite-Taiwan: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/taiwan.mrs" }
  GeoSite-TikTok: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/tiktok.mrs" }
  GeoSite-YouTube: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/youtube.mrs" }
  GeoSite-E-Hentai: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/ehentai.mrs" }
  GeoSite-Sniffer-Filter: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/sniffer-filter.mrs" }
  GeoSite-FakeIP-Filter: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/mihomo/geo/geosite/fake-ip-filter.mrs" }
  GeoSite-AdBlock: { <<: *DOMAIN, url: "https://v6.gh-proxy.org/github.com/MissToT/rule-set/raw/adblock/mihomo.mrs" }

rules:
  - DST-PORT,53,🔰 DNS-Hijack
  - RULE-SET,GeoSite-AdBlock,广告拦截
  - RULE-SET,GeoSite-Private,🌐 本地直连
  - RULE-SET,GeoSite-GoogleFCM,谷歌推送
  - RULE-SET,GeoSite-Telegram,Telegram
  - RULE-SET,GeoSite-Twitter,Twitter
  - RULE-SET,GeoSite-TikTok,TikTok
  - RULE-SET,GeoSite-AI,AI
  - RULE-SET,GeoSite-YouTube,YouTube
  - RULE-SET,GeoSite-Emby,Emby
  - RULE-SET,GeoSite-E-Hentai,E-Hentai
  - RULE-SET,GeoSite-Games,Games
  - RULE-SET,GeoSite-Japan,日本网站
  - RULE-SET,GeoSite-Taiwan,台湾网站
  - RULE-SET,GeoSite-Google,Google
  - RULE-SET,GeoSite-Cloudflare,Cloudflare
  - RULE-SET,GeoSite-Proxy,国外代理
  - RULE-SET,GeoSite-China,国内直连
  - RULE-SET,GeoIP-Private,🌐 本地直连,no-resolve
  - RULE-SET,GeoIP-Telegram,Telegram,no-resolve
  - RULE-SET,GeoIP-Twitter,Twitter,no-resolve
  - RULE-SET,GeoIP-AI,AI,no-resolve
  - RULE-SET,GeoIP-Google,Google,no-resolve
  - RULE-SET,GeoIP-Cloudflare,Cloudflare,no-resolve
  - RULE-SET,GeoIP-Proxy,国外代理,no-resolve
  - RULE-SET,GeoIP-China,国内直连,no-resolve
  - MATCH,漏网之鱼